import os
from launch import LaunchDescription
from launch.actions import ExecuteProcess
from ament_index_python.packages import get_package_share_directory

def generate_launch_description():

    pkg_nav  = get_package_share_directory("robot_navigation")
    map_path = os.path.join(pkg_nav, "maps", "map")

    return LaunchDescription([

        # Save the map generated by SLAM toolbox
        ExecuteProcess(
            cmd=["ros2", "run", "nav2_map_server", "map_saver_cli",
                 "-f", map_path,
                 "--ros-args", "-p", "use_sim_time:=true"],
            output="screen"
        ),
    ])
